name: Flutter_iOS1

on:
  push:
    branches: [main]

jobs:
  build_ios:
    runs-on: macos-latest

    steps:
      - name: Checkout the code
        uses: actions/checkout@v2

      - name: Clean Derived Data
        run: |
          rm -rf ~/Library/Developer/Xcode/DerivedData

      - name: Install Apple Certificate
        uses: apple-actions/import-codesign-certs@v1
        with:
          p12-file-base64: ${{ secrets.P12_BASE64 }}
          p12-password: ${{ secrets.P12_PASSWORD }}

      - name: Install the provisioning profile
        env:
          PROVISIONING_CERTIFICATE_BASE64: ${{ secrets.IOS_PROVISION_3 }}
        run: |
          PP_PATH=$RUNNER_TEMP/build_pp.mobileprovision
          echo -n "$PROVISIONING_CERTIFICATE_BASE64" | base64 --decode --output $PP_PATH
          mkdir -p ~/Library/MobileDevice/Provisioning\ Profiles
          cp $PP_PATH ~/Library/MobileDevice/Provisioning\ Profiles

      - name: Install and set Flutter version
        uses: subosito/flutter-action@v2
        with:
          flutter-version: 3.16

      - name: Restore packages
        run: flutter pub get

      - name: Clean Xcode Project
        run: xcodebuild clean -workspace ios/Runner.xcworkspace -scheme DEV -configuration Release-DEV

      - name: Reinstall CocoaPods
        run: |
          flutter clean
          flutter pub get
          cd ios
          pod install
          pod update

      - name: Build resolve Swift dependencies
        run: xcodebuild -resolvePackageDependencies -workspace ios/Runner.xcworkspace -scheme DEV -configuration Release-DEV

      - name: Print current working directory
        run: pwd

      - name: List contents of the directory
        run: ls -ltr

      - name: Build and export .ipa (Release Mode)
        run: |
          xcodebuild -workspace ios/Runner.xcworkspace -scheme DEV -configuration Release-DEV -sdk iphoneos -destination 'generic/platform=iOS' -archivePath build-output/app.xcarchive PROVISIONING_PROFILE_SPECIFIER="Mobilewisedistribution" clean archive CODE_SIGN_IDENTITY="Apple Distribution: Laxmiprasad Putta"
          xcodebuild -exportArchive -archivePath build-output/app.xcarchive -exportPath build-output/ios -exportOptionsPlist ios/ExportOptions.plist

      
      - name: Run Flutter in Release Mode
        run: flutter build ipa --release


      - name: Upload build artifacts
        uses: actions/upload-artifact@v2
        with:
          name: ios-build
          path: build-output/ios
