# Uncomment this line to define a global platform for your project
platform :ios, '12.0'

# ... rest of your Podfile code

target 'Runner' do
  use_frameworks!
  use_modular_headers!

  flutter_install_all_ios_pods File.dirname(File.realpath(__FILE__))

  # --- Remove or Comment Out the RunnerTests Block ---
  # target 'RunnerTests' do
  #   inherit! :search_paths
  # end
end
