# Uncomment this line to define a global platform for your project
platform :ios, '12.0'

# Suppress all warnings from all pods
inhibit_all_warnings!

target 'Runner' do
  # Specify the platform for the Runner target
  platform :ios, '12.0'

  # Add your Flutter pod dependencies
  use_frameworks!
  use_modular_headers!
  flutter_install_all_ios_pods File.dirname(File.realpath(__FILE__))
end
