name: Generate Signed iOS IPA

on:
  push:
    branches: [main]  

jobs:
  build_signed_ipa:
    runs-on: macos-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Install Apple Certificate
        uses: apple-actions/import-codesign-certs@v1
        with:
          p12-file-base64: ${{ secrets.P12_BASE64 }} 
          p12-password: ${{ secrets.P12_PASSWORD }}

      - name: Install Provisioning Profile
        env:
          PROVISIONING_PROFILE_BASE64: ${{ secrets.IOS_PROVISION_2 }} 
        run: |
          # Create temporary files for certificates and profiles (optional)
          PP_PATH=$RUNNER_TEMP/ios_distribution.mobileprovision 
          echo -n "$PROVISIONING_PROFILE_BASE64" | base64 --decode --output $PP_PATH
          mkdir -p ~/Library/MobileDevice/Provisioning\ Profiles
          cp $PP_PATH ~/Library/MobileDevice/Provisioning\ Profiles

      - name: Setup Flutter Environment
        uses: subosito/flutter-action@v2
        with:
          flutter-version: '3.16.3' 

      - name: Restore Flutter Packages
        run: flutter pub get

      - name: Build Signed iOS Release App (xcodebuild)
        run: |
          xcodebuild -workspace ios/Runner.xcworkspace \
                     -scheme Runner \ 
                     -configuration Release \
                     -archivePath build/ios/Runner.xcarchive \
                     archive CODE_SIGN_IDENTITY="Apple Distribution: Laxmiprasad Putta (4RD8TSB5PJ)"

      - name: Create IPA  # Add this subsequent step
        run: |
          xcodebuild -exportArchive \
                     -archivePath build/ios/Runner.xcarchive \
                     -exportOptionsPlist ios/ExportOptions.plist \
                     -exportPath build/ios/ipa

      - name: Upload Signed IPA as Artifact
        uses: actions/upload-artifact@v3
        with:
          name: signed-ios-app.ipa
          path: build/ios/ipa/Runner.ipa 
