name: Build IPA from Runner.xcarchive

on:
  workflow_dispatch:
    branches: [main]

jobs:
  build_ios_adhoc:
    runs-on: macos-latest

    steps:
      - name: Checkout the code
        uses: actions/checkout@v2

      - name: Install Flutter
        uses: subosito/flutter-action@v2
        with:
          flutter-version: '3.16'
          channel: 'stable'
          cache: true

      - name: Set up Code Signing 
        uses: apple-actions/import-codesign-certs@v1
        with:
          p12-file-base64: ${{ secrets.IOS_DISTRIBUTION }}
          p12-password: ${{ secrets.IOS_PASSWORD }}

      - name: Install Provisioning Profile
        env:
          PROVISIONING_PROFILE_BASE64: ${{ secrets.NEW_DISTRIBUTION_IOS }}
        run: |
          PP_PATH=$RUNNER_TEMP/NEW_DISTRIBUTION_IOS.mobileprovision
          echo -n "$PROVISIONING_PROFILE_BASE64" | base64 --decode --output $PP_PATH
          mkdir -p ~/Library/MobileDevice/Provisioning\ Profiles
          cp $PP_PATH ~/Library/MobileDevice/Provisioning\ Profiles

      - name:  Flutter setup and dependencies
        run: |
          flutter clean
          flutter pub get
          cd ios 
          rm -rf Pods/ Podfile.lock
          pod deintegrate
          pod install 
          cd ..

      - name: Clean and Build Xcode Project
        run: xcodebuild clean build -workspace ios/Runner.xcworkspace -scheme Runner -configuration Release

      - name: Create IPA directory
        run: mkdir -p IPA

      - name: Build xcarchive
        run: xcodebuild archive -workspace ios/Runner.xcworkspace -configuration Release -archivePath IPA/Runner.xcarchive -exportOptionsPlist ExportOptions.plist -exportArchive
      
      - name: Extract Runner.app from xcarchive
        run: |
          mkdir -p IPA/Payload
          cp -R IPA/Runner.xcarchive/Products/Applications/Runner.app IPA/Payload

      - name: Create IPA from Runner.app
        run: |
          cd IPA
          zip -qyr MobileWise.ipa Payload
          rm -rf Payload

      - name: Verify IPA contents
        run: unzip -l IPA/MobileWise.ipa

      - name: Upload IPA as artifact
        uses: actions/upload-artifact@v2 
        with:
          name: ios-ipa
          path: IPA/MobileWise.ipa
