name: Build & Sign iOS App

on: 
  push:
    branches: [ master, main ] 

jobs:
  build:
    runs-on: macos-latest  

    steps:
      - uses: actions/checkout@v3
      - uses: ruby/setup-ruby@v1
        with:
          ruby-version: '3.1.4' 
      - run: bundle install

      - name: Install Certificates and Profiles
        env:
          CERT_BASE64: ${{ secrets.P12_BASE64}}
          CERT_PASSWORD: ${{ secrets.P12_PASSWORD}}
          PROFILE_BASE64: ${{ secrets.IOS_PROVISION_1}}
        run: |
          create_keychain name: codesigning password: "temp_password" default_keychain: true unlock: true 

          echo $P12_BASE64 | base64 --decode > certificate.cer
          import_certificate certificate_path: "certificate.cer" keychain_path: "$HOME/Library/Keychains/codesigning" -k $CERT_PASSWORD

          echo $IOS_PROVISION_1 | base64 --decode > profile.mobileprovision
          uuid=`/usr/libexec/PlistBuddy -c "Print UUID" profile.mobileprovision`
          import_profile profile_path: "profile.mobileprovision" uuid: $uuid keychain_path: "$HOME/Library/Keychains/codesigning"  

      - run: fastlane build_ipa 

      - name: Upload Artifact
        uses: actions/upload-artifact@v3
        with:
          name: ios-app.ipa
          path: path/to/your/built.ipa 
