name: Generate Signed iOS IPA

on: 
  workflow_dispatch:  # Manually trigger builds

jobs:
  build_signed_ipa:
    runs-on: macos-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Install Apple Certificate
        uses: apple-actions/import-codesign-certs@v1
        with:
          p12-file-base64: ${{ secrets.P12_BASE64 }} 
          p12-password: ${{ secrets.P12_PASSWORD }}

      - name: Install Provisioning Profile
        env:
          PROVISIONING_PROFILE_BASE64: ${{ secrets.IOS_PROVISION_1 }} 
        run: |
          # Create temporary files for certificates and profiles
          PP_PATH=$RUNNER_TEMP/ios_distribution.mobileprovision
          echo -n "$PROVISIONING_PROFILE_BASE64" | base64 --decode --output $PP_PATH
          mkdir -p ~/Library/MobileDevice/Provisioning\ Profiles
          cp $PP_PATH ~/Library/MobileDevice/Provisioning\ Profiles

      - name: Setup Flutter Environment
        uses: subosito/flutter-action@v2
        with:
          flutter-version: '3.3.2' # Adjust if needed

      - name: Restore Flutter Packages
        run: flutter pub get

      - name: Build Signed iOS Release App
        run: flutter build ipa --release  # Use specific target/scheme if needed

      - name: Upload Signed IPA as Artifact
        uses: actions/upload-artifact@v3
        with:
          name: signed-ios-app.ipa
          path: build/ios/ipa/Runner.ipa  
