name: Generate Signed iOS IPA

on:
  push:
    branches: [main]  

jobs:
  build_signed_ipa:
    runs-on: macos-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Install Apple Certificate
        uses: apple-actions/import-codesign-certs@v1
        with:
          p12-file-base64: ${{ secrets.P12_BASE64 }} 
          p12-password: ${{ secrets.P12_PASSWORD }}

      - name: Install Provisioning Profile
        env:
          PROVISIONING_PROFILE_BASE64: ${{ secrets.NEWMOBILEWISEDISTRIBUTION }} 
        run: |
          # Create temporary files for certificates and profiles (optional)
          PP_PATH=$RUNNER_TEMP/ios_distribution.mobileprovision 
          echo -n "$PROVISIONING_PROFILE_BASE64" | base64 --decode --output $PP_PATH
          mkdir -p ~/Library/MobileDevice/Provisioning\ Profiles
          cp $PP_PATH ~/Library/MobileDevice/Provisioning\ Profiles

      - name: Setup Flutter Environment
        uses: subosito/flutter-action@v2
        with:
          flutter-version: '3.16.3' 

      - name: Check Flutter SDK Installation
        run: flutter --version

  #    - name: Update Flutter SDK
   #     run: flutter upgrade

      - name: Reinstall Flutter Dependencies
        run: flutter pub get

      - name: Clear Flutter Cache
        run: flutter clean

      - name: Deintegrate CocoaPods and Reinstall
        run: |
          cd ios
          pod deintegrate
          rm Podfile
          echo "platform :ios, '12.0'" > Podfile
          echo "target 'Runner' do" >> Podfile
          echo "  use_frameworks!" >> Podfile
          echo "end" >> Podfile
          pod install
          cd ..

      - name: Clean Xcode Project
        run: xcodebuild clean -workspace ios/Runner.xcworkspace -scheme Runner -configuration Release

      - name: Build and Resolve Swift Dependencies
        run: xcodebuild -resolvePackageDependencies -workspace ios/Runner.xcworkspace -scheme Runner -configuration Release

      - name: Print Current Working Directory
        run: pwd

      - name: List Contents of the Directory
        run: ls

      - name: Build and Export .ipa (Distribution)
        run: |
          xcrun xcodebuild -workspace ios/Runner.xcworkspace -configuration Debug -scheme Runner VERBOSE_SCRIPT_LOGGING=YES COMPILER_INDEX_STORE_ENABLE=NO EXCLUDED_ARCHS=arm64 PROVISIONING_PROFILE_SPECIFIER='NewMobilewiseDistribution'
          xcodebuild -exportArchive -archivePath build-output/app.xcarchive -exportPath build-output/ios -exportOptionsPlist ios/ExportOptions.plist


      - name: Upload Build Artifacts (Distribution)
        uses: actions/upload-artifact@v2
        with:
          name: ios-build-distribution
          path: build-output/ios
