name: Build & Sign iOS App

on:
  push:
    branches: [ main ] 

jobs:
  build:
    runs-on: macos-latest  

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Install Ruby and Bundler
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: '3.1.4'

      - name: Install Fastlane
        run: |
          gem install fastlane -NV
          export PATH="$HOME/.fastlane/bin:$PATH"

      - name: Install Certificates and Profiles
        env:
          CERT_BASE64: ${{ secrets.P12_BASE64 }}
          CERT_PASSWORD: ${{ secrets.P12_PASSWORD }}
          PROFILE_BASE64: ${{ secrets.IOS_PROVISION_1 }}
        run: |
          # Decode the certificate and provisioning profile
          echo "$CERT_BASE64" | base64 --decode > certificate.p12
          echo "$PROFILE_BASE64" | base64 --decode > profile.mobileprovision

          # Create a new keychain, import the certificate, and set it as default
          security create-keychain -p temp_password codesigning.keychain
          security import certificate.p12 -k ~/Library/Keychains/codesigning.keychain -P "$CERT_PASSWORD" -T /usr/bin/codesign
          security set-key-partition-list -S apple-tool:,apple: -s -k temp_password ~/Library/Keychains/codesigning.keychain
          security list-keychains -s ~/Library/Keychains/codesigning.keychain
          security unlock-keychain -p temp_password ~/Library/Keychains/codesigning.keychain

          # Extract the UUID from the provisioning profile
          uuid=$(grep -a -A1 UUID profile.mobileprovision | grep -o "[-a-zA-Z0-9]\{36\}")
          echo "UUID: $uuid"

          # Copy the provisioning profile to the appropriate directory
          mkdir -p ~/Library/MobileDevice/Provisioning\ Profiles
          cp profile.mobileprovision ~/Library/MobileDevice/Provisioning\ Profiles/$uuid.mobileprovision

      - name: Build IPA using Fastlane
        run: fastlane build

      - name: Upload Artifact
        uses: actions/upload-artifact@v3
        with:
          name: ios-app.ipa
          path: path/to/your/built.ipa
