name: Build & Sign iOS App

on: 
  push:
    branches: [master, main]

jobs:
  build:
    runs-on: macos-latest

    steps:
      - uses: actions/checkout@v3

      # Gemfile and Fastlane Setup
      - name: Create Gemfile and Install Fastlane
        run: |
          cd ios 
          bundle init
          echo 'gem "fastlane"' >> Gemfile
          bundle install

      # Ruby Setup
      - uses: ruby/setup-ruby@v1
        with:
          ruby-version: '3.1.4'

      # Install Certificate
      - name: Install Certificate 
        env:
          P12_BASE64: ${{ secrets.P12_BASE64 }}
          CERT_PASSWORD: ${{ secrets.P12_PASSWORD }}
        run: |
          create_keychain name: codesigning password: "temp_password" default_keychain: true unlock: true
          echo $P12_BASE64 | base64 --decode > certificate.cer
          import_certificate certificate_path: "certificate.cer" keychain_path: "$HOME/Library/Keychains/codesigning" -k $CERT_PASSWORD

      # Build and Sign
      - run: fastlane build_ipa

      # Artifact Upload
      - name: Upload Artifact
        uses: actions/upload-artifact@v3
        with:
          name: ios-app.ipa
          path: path/to/your/built.ipa 
